[build-system]
requires = ['setuptools>=40.8.0']
build-backend = 'setuptools.build_meta'

[project]
name = "django-bunny-m"
version = "0.1.2"
authors = [
  { name="Zwiezda", email="kuba_drapiewski@protonmail.com" },
]
description = "A Django module to RabbitMQ communication"
readme = {file = "README.rst", content-type = "text/x-rst"}
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Zwiezda/django-bunny-m"
Issues = "https://github.com/Zwiezda/django-bunny-m/issues"
